version: '3'
services:
  nicegui:
    build:
      context: .
      dockerfile: Dockerfile
    command: python app/main.py
    volumes:
      - .:/nicegui-app
    ports:
      - '8000:8000'
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
